02 - Desenvolvimento/ephynances/config/routes.rb
Rails.application.routes.draw do
  resources :regions, only: [:index]

  resources :states, only: [:index]

  resources :agreement_documents

  resources :agreement_installments

  resources :agreement_responsibles

  resources :agreement_types, only: [:index]

  resources :agreements

  resources :city_organs

  resources :user_levels, only: [:index]

  resources :users

  root 'home#index'

end

02 - Desenvolvimento/ephynances/app/models/agreement.rb
# encoding: UTF-8
class Agreement < ActiveRecord::Base

  validates_presence_of :totalPrice, :contractorAgreementNumber, :physisAgreementNumber, :expiryDate, :status
  validates_uniqueness_of :contractorAgreementNumber, :physisAgreementNumber

  has_many :agreement_installments
  has_many :agreement_documents
  belongs_to :agreement_responsible
  belongs_to :agreement_type
  belongs_to :user
end

02 - Desenvolvimento/ephynances/app/models/agreement_document.rb
# encoding: UTF-8
class AgreementDocument < ActiveRecord::Base

  validates_presence_of :name, :description, :size, :file
  validates_length_of :description, maximum: 500, allow_blank: false

  belongs_to :agreement
end

02 - Desenvolvimento/ephynances/app/models/agreement_installment.rb
# encoding: UTF-8
class AgreementInstallment < ActiveRecord::Base

  validates_presence_of :value, :status, :dueDate

  belongs_to :agreement
  has_many :sub_agreement_installments
  belongs_to :payment
end

02 - Desenvolvimento/ephynances/app/models/agreement_type.rb
# encoding: UTF-8
class AgreementType < ActiveRecord::Base

  validates_presence_of :agreementType
  validates_uniqueness_of :agreementType

  has_many :agreements
end

02 - Desenvolvimento/ephynances/app/models/city_organ.rb
# encoding: UTF-8
class CityOrgan < ActiveRecord::Base

  validates_presence_of :cnpj, :cityName, :organName
  validates_uniqueness_of :cnpj

  has_many :users
  has_many :agreements
  belongs_to :state
end

02 - Desenvolvimento/ephynances/app/models/payment.rb
# encoding: UTF-8
class Payment < ActiveRecord::Base

  validates_presence_of :value, :paymentDate, :confirmationDate, :status

  has_one :agreement_installment
  has_one :sub_agreement_installment
  has_many :payment_documents
end

02 - Desenvolvimento/ephynances/app/models/payment_document.rb
# encoding: UTF-8
class PaymentDocument < ActiveRecord::Base

  validates_presence_of :name, :file, :extension, :description, :size
  validates_length_of :description, maximum: 500, allow_blank: false

  belongs_to :payment
end

02 - Desenvolvimento/ephynances/app/models/recover_password.rb
# encoding: UTF-8
class RecoverPassword < ActiveRecord::Base

  validates_presence_of :token, :validity
  validates_uniqueness_of :token
end

02 - Desenvolvimento/ephynances/app/models/region.rb
# encoding: UTF-8
class Region < ActiveRecord::Base

  validates_presence_of :name, :acronym
  validates_uniqueness_of :name, :acronym

  has_many :states
end

02 - Desenvolvimento/ephynances/app/models/state.rb
# encoding: UTF-8
class State < ActiveRecord::Base

  validates_presence_of :name, :acronym
  validates_uniqueness_of :name, :acronym

  has_many :city_organs
  belongs_to :region
end

02 - Desenvolvimento/ephynances/app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base
  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  validates_presence_of :email, :name, :login, :cpf, :maxSalesAmount
  validates_format_of :email, with: EMAIL_REGEXP
  validates_uniqueness_of :email, :cpf, :login
  validates_length_of :cpf, minimum: 11, maximum: 11

  has_secure_password
  belongs_to :user_level
  has_many :agreements
end

02 - Desenvolvimento/ephynances/app/models/user_has_contributor.rb
# encoding: UTF-8
class UserHasContributor < ActiveRecord::Base

  validates_presence_of :vendor_user_id, :contributor_user_id

end

02 - Desenvolvimento/ephynances/app/models/user_level.rb
# encoding: UTF-8
class UserLevel < ActiveRecord::Base

  validates_presence_of :levelType
  validates_uniqueness_of :levelType

  has_many :users
end

02 - Desenvolvimento/ephynances/app/controllers/agreement_installments_controller.rb
# encoding: UTF-8
class AgreementInstallmentsController < ApplicationController
  before_action :set_agreement_installment, only: [:show, :edit, :update, :destroy]

  # GET /agreement_installments
  # GET /agreement_installments.json
  def index
    @agreement_installments = AgreementInstallment.all
  end

  # GET /agreement_installments/1
  # GET /agreement_installments/1.json
  def show
  end

  # GET /agreement_installments/new
  def new
    @agreement_installment = AgreementInstallment.new
  end

  # GET /agreement_installments/1/edit
  def edit
  end

  # POST /agreement_installments
  # POST /agreement_installments.json
  def create
    @agreement_installment = AgreementInstallment.new(agreement_installment_params)

    respond_to do |format|
      if @agreement_installment.save
        format.html { redirect_to @agreement_installment, notice: 'Agreement installment was successfully created.' }
        format.json { render :show, status: :created, location: @agreement_installment }
      else
        format.html { render :new }
        format.json { render json: @agreement_installment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agreement_installments/1
  # PATCH/PUT /agreement_installments/1.json
  def update
    respond_to do |format|
      if @agreement_installment.update(agreement_installment_params)
        format.html { redirect_to @agreement_installment, notice: 'Agreement installment was successfully updated.' }
        format.json { render :show, status: :ok, location: @agreement_installment }
      else
        format.html { render :edit }
        format.json { render json: @agreement_installment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agreement_installments/1
  # DELETE /agreement_installments/1.json
  def destroy
    @agreement_installment.destroy
    respond_to do |format|
      format.html { redirect_to agreement_installments_url, notice: 'Agreement installment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agreement_installment
      @agreement_installment = AgreementInstallment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agreement_installment_params
      params.require(:agreement_installment).permit(:value, :status, :paymentDate, :dueDate, :confirmationDate)
    end
end

02 - Desenvolvimento/ephynances/app/controllers/home_controller.rb
# encoding: UTF-8
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

02 - Desenvolvimento/ephynances/app/helpers/agreement_installments_helper.rb
# encoding: UTF-8
module AgreementInstallmentsHelper
end

02 - Desenvolvimento/ephynances/app/helpers/agreements_helper.rb
# encoding: UTF-8
module AgreementsHelper
end

02 - Desenvolvimento/ephynances/app/helpers/application_helper.rb
# encoding: UTF-8
module ApplicationHelper
end

02 - Desenvolvimento/ephynances/app/helpers/city_organs_helper.rb
# encoding: UTF-8
module CityOrgansHelper
end

02 - Desenvolvimento/ephynances/app/helpers/regions_helper.rb
# encoding: UTF-8
module RegionsHelper
end

02 - Desenvolvimento/ephynances/app/helpers/states_helper.rb
# encoding: UTF-8
module StatesHelper
end

02 - Desenvolvimento/ephynances/app/helpers/user_levels_helper.rb
# encoding: UTF-8
module UserLevelsHelper
end

02 - Desenvolvimento/ephynances/app/helpers/users_helper.rb
# encoding: UTF-8
module UsersHelper
end

02 - Desenvolvimento/ephynances/app/views/agreement_installments/_form.html.erb
<%= form_for(@agreement_installment) do |f| %>
  <% if @agreement_installment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agreement_installment.errors.count, "error") %> prohibited this agreement_installment from being saved:</h2>

      <ul>
      <% @agreement_installment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :paymentDate %><br>
    <%= f.date_select :paymentDate %>
  </div>
  <div class="field">
    <%= f.label :dueDate %><br>
    <%= f.date_select :dueDate %>
  </div>
  <div class="field">
    <%= f.label :confirmationDate %><br>
    <%= f.date_select :confirmationDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

02 - Desenvolvimento/ephynances/app/views/agreement_installments/edit.html.erb
<h1>Editing Agreement Installment</h1>

<%= render 'form' %>

<%= link_to 'Show', @agreement_installment %> |
<%= link_to 'Back', agreement_installments_path %>

02 - Desenvolvimento/ephynances/app/views/agreement_installments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agreement Installments</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Status</th>
      <th>Paymentdate</th>
      <th>Duedate</th>
      <th>Confirmationdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agreement_installments.each do |agreement_installment| %>
      <tr>
        <td><%= agreement_installment.value %></td>
        <td><%= agreement_installment.status %></td>
        <td><%= agreement_installment.paymentDate %></td>
        <td><%= agreement_installment.dueDate %></td>
        <td><%= agreement_installment.confirmationDate %></td>
        <td><%= link_to 'Show', agreement_installment %></td>
        <td><%= link_to 'Edit', edit_agreement_installment_path(agreement_installment) %></td>
        <td><%= link_to 'Destroy', agreement_installment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agreement installment', new_agreement_installment_path %>

02 - Desenvolvimento/ephynances/app/views/agreement_installments/new.html.erb
<h1>New Agreement Installment</h1>

<%= render 'form' %>

<%= link_to 'Back', agreement_installments_path %>

02 - Desenvolvimento/ephynances/app/views/agreement_installments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @agreement_installment.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @agreement_installment.status %>
</p>

<p>
  <strong>Paymentdate:</strong>
  <%= @agreement_installment.paymentDate %>
</p>

<p>
  <strong>Duedate:</strong>
  <%= @agreement_installment.dueDate %>
</p>

<p>
  <strong>Confirmationdate:</strong>
  <%= @agreement_installment.confirmationDate %>
</p>

<%= link_to 'Edit', edit_agreement_installment_path(@agreement_installment) %> |
<%= link_to 'Back', agreement_installments_path %>