02 - Desenvolvimento/ephynances/config/routes.rb
Rails.application.routes.draw do
  resources :regions, only: [:index]

  resources :states, only: [:index]

  resources :agreement_documents

  resources :agreement_installments

  resources :agreement_responsibles

  resources :agreement_types, only: [:index]

  resources :agreements

  resources :city_organs

  resources :user_levels, only: [:index]

  resources :users

  root 'home#index'

end

02 - Desenvolvimento/ephynances/app/models/region.rb
# encoding: UTF-8
class Region < ActiveRecord::Base

  validates_presence_of :name, :acronym
  validates_uniqueness_of :name, :acronym

  has_many :states
end

02 - Desenvolvimento/ephynances/app/controllers/regions_controller.rb
# encoding: UTF-8
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :acronym)
    end
end

02 - Desenvolvimento/ephynances/app/helpers/regions_helper.rb
# encoding: UTF-8
module RegionsHelper
end

02 - Desenvolvimento/ephynances/app/views/regions/_form.html.erb
<%= form_for(@region) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% @region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :acronym %><br>
    <%= f.text_field :acronym %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

02 - Desenvolvimento/ephynances/app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

02 - Desenvolvimento/ephynances/app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Regions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Acronym</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= region.acronym %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>

02 - Desenvolvimento/ephynances/app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

02 - Desenvolvimento/ephynances/app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @region.name %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @region.acronym %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>