02 - Desenvolvimento/ephynances/config/routes.rb
Rails.application.routes.draw do
  resources :regions, only: [:index]

  resources :states, only: [:index]

  resources :agreement_documents

  resources :agreement_installments

  resources :agreement_responsibles

  resources :agreement_types, only: [:index]

  resources :agreements

  resources :city_organs

  resources :user_levels, only: [:index]

  resources :users

  root 'home#index'

end

02 - Desenvolvimento/ephynances/app/models/city_organ.rb
# encoding: UTF-8
class CityOrgan < ActiveRecord::Base

  validates_presence_of :cnpj, :cityName, :organName
  validates_uniqueness_of :cnpj

  has_many :users
  has_many :agreements
  belongs_to :state
end

02 - Desenvolvimento/ephynances/app/controllers/city_organs_controller.rb
# encoding: UTF-8
class CityOrgansController < ApplicationController
  before_action :set_city_organ, only: [:show, :edit, :update, :destroy]

  # GET /city_organs
  # GET /city_organs.json
  def index
    @city_organs = CityOrgan.all
  end

  # GET /city_organs/1
  # GET /city_organs/1.json
  def show
  end

  # GET /city_organs/new
  def new
    @city_organ = CityOrgan.new
  end

  # GET /city_organs/1/edit
  def edit
  end

  # POST /city_organs
  # POST /city_organs.json
  def create
    @city_organ = CityOrgan.new(city_organ_params)

    respond_to do |format|
      if @city_organ.save
        format.html { redirect_to @city_organ, notice: 'City organ was successfully created.' }
        format.json { render :show, status: :created, location: @city_organ }
      else
        format.html { render :new }
        format.json { render json: @city_organ.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /city_organs/1
  # PATCH/PUT /city_organs/1.json
  def update
    respond_to do |format|
      if @city_organ.update(city_organ_params)
        format.html { redirect_to @city_organ, notice: 'City organ was successfully updated.' }
        format.json { render :show, status: :ok, location: @city_organ }
      else
        format.html { render :edit }
        format.json { render json: @city_organ.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /city_organs/1
  # DELETE /city_organs/1.json
  def destroy
    @city_organ.destroy
    respond_to do |format|
      format.html { redirect_to city_organs_url, notice: 'City organ was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city_organ
      @city_organ = CityOrgan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_organ_params
      params.require(:city_organ).permit(:cnpj, :cityName, :stateName, :regionName, :organName)
    end
end

02 - Desenvolvimento/ephynances/app/helpers/city_organs_helper.rb
# encoding: UTF-8
module CityOrgansHelper
end

02 - Desenvolvimento/ephynances/app/views/city_organs/_form.html.erb
<%= form_for(@city_organ) do |f| %>
  <% if @city_organ.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city_organ.errors.count, "error") %> prohibited this city_organ from being saved:</h2>

      <ul>
      <% @city_organ.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :cityName %><br>
    <%= f.text_field :cityName %>
  </div>
  <div class="field">
    <%= f.label :stateName %><br>
    <%= f.text_field :stateName %>
  </div>
  <div class="field">
    <%= f.label :regionName %><br>
    <%= f.text_field :regionName %>
  </div>
  <div class="field">
    <%= f.label :organName %><br>
    <%= f.text_field :organName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

02 - Desenvolvimento/ephynances/app/views/city_organs/edit.html.erb
<h1>Editing City Organ</h1>

<%= render 'form' %>

<%= link_to 'Show', @city_organ %> |
<%= link_to 'Back', city_organs_path %>

02 - Desenvolvimento/ephynances/app/views/city_organs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing City Organs</h1>

<table>
  <thead>
    <tr>
      <th>Cnpj</th>
      <th>Cityname</th>
      <th>Statename</th>
      <th>Regionname</th>
      <th>Organname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @city_organs.each do |city_organ| %>
      <tr>
        <td><%= city_organ.cnpj %></td>
        <td><%= city_organ.cityName %></td>
        <td><%= city_organ.stateName %></td>
        <td><%= city_organ.regionName %></td>
        <td><%= city_organ.organName %></td>
        <td><%= link_to 'Show', city_organ %></td>
        <td><%= link_to 'Edit', edit_city_organ_path(city_organ) %></td>
        <td><%= link_to 'Destroy', city_organ, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City organ', new_city_organ_path %>

02 - Desenvolvimento/ephynances/app/views/city_organs/new.html.erb
<h1>New City Organ</h1>

<%= render 'form' %>

<%= link_to 'Back', city_organs_path %>

02 - Desenvolvimento/ephynances/app/views/city_organs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cnpj:</strong>
  <%= @city_organ.cnpj %>
</p>

<p>
  <strong>Cityname:</strong>
  <%= @city_organ.cityName %>
</p>

<p>
  <strong>Statename:</strong>
  <%= @city_organ.stateName %>
</p>

<p>
  <strong>Regionname:</strong>
  <%= @city_organ.regionName %>
</p>

<p>
  <strong>Organname:</strong>
  <%= @city_organ.organName %>
</p>

<%= link_to 'Edit', edit_city_organ_path(@city_organ) %> |
<%= link_to 'Back', city_organs_path %>